# Generated by Django 4.1 on 2022-12-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0002_studentdata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
