# Generated by Django 4.1 on 2022-12-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_studentdata_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='phone_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
